#!/usr/bin/env bash
set -euo pipefail

# Deploy ChainCred contracts to a local Anvil fork.
# Writes contract addresses to .env.anvil at project root.
#
# Usage: bash packages/contracts/script/deploy-anvil.sh

cd "$(dirname "$0")/.."

# Anvil default account 0
DEPLOYER_PRIVATE_KEY="${DEPLOYER_PRIVATE_KEY:-0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80}"
RPC_URL="${RPC_URL:-http://localhost:8545}"
EAS_ADDRESS="${EAS_ADDRESS:-0xA1207F3BBa224E2c9c3c6D5aF63D0eb1582Ce587}"

# Burn address to mark as excluded
EXCLUDED_ADDRESS="0x000000000000000000000000000000000000dEaD"

echo "=== ChainCred Anvil Deployment ==="
echo "RPC:  $RPC_URL"
echo "EAS:  $EAS_ADDRESS"
echo ""

# Verify Anvil is reachable
if ! cast block-number --rpc-url "$RPC_URL" > /dev/null 2>&1; then
  echo "Error: Cannot reach Anvil at $RPC_URL"
  exit 1
fi

# Deploy contracts
echo "Deploying contracts..."
export DEPLOYER_PRIVATE_KEY EAS_ADDRESS
DEPLOY_OUTPUT=$(forge script script/Deploy.s.sol:Deploy \
  --rpc-url "$RPC_URL" \
  --broadcast \
  -vvv 2>&1) || {
    echo "Deployment failed:"
    echo "$DEPLOY_OUTPUT"
    exit 1
  }

echo "$DEPLOY_OUTPUT" | tail -20

# Extract addresses from forge output
REGISTRY=$(echo "$DEPLOY_OUTPUT" | grep "Registry:" | awk '{print $2}')
MERKLE=$(echo "$DEPLOY_OUTPUT" | grep "MerkleRoot:" | awk '{print $2}')
RESOLVER=$(echo "$DEPLOY_OUTPUT" | grep "BadgeResolver:" | awk '{print $2}')

if [[ -z "$REGISTRY" || -z "$MERKLE" || -z "$RESOLVER" ]]; then
  echo "Error: Could not extract contract addresses from output"
  echo "Full output:"
  echo "$DEPLOY_OUTPUT"
  exit 1
fi

echo ""
echo "Registry:      $REGISTRY"
echo "MerkleRoot:    $MERKLE"
echo "BadgeResolver: $RESOLVER"

# Set burn address as excluded in Registry (owner == deployer)
echo ""
echo "Setting $EXCLUDED_ADDRESS as excluded..."
cast send "$REGISTRY" "setExcluded(address,bool)" "$EXCLUDED_ADDRESS" true \
  --rpc-url "$RPC_URL" \
  --private-key "$DEPLOYER_PRIVATE_KEY" \
  > /dev/null 2>&1

# Verify exclusion
IS_EXCLUDED=$(cast call "$REGISTRY" "excludedAddresses(address)(bool)" "$EXCLUDED_ADDRESS" \
  --rpc-url "$RPC_URL" 2>/dev/null || echo "false")
echo "  excludedAddresses($EXCLUDED_ADDRESS) = $IS_EXCLUDED"

# Write .env.anvil at project root
ENV_FILE="$(git rev-parse --show-toplevel)/.env.anvil"
cat > "$ENV_FILE" <<EOF
# Auto-generated by deploy-anvil.sh — do not edit
CHAINCRED_REGISTRY_ADDRESS=$REGISTRY
SCORE_MERKLE_ADDRESS=$MERKLE
BADGE_RESOLVER_ADDRESS=$RESOLVER
RPC_URL=$RPC_URL
EAS_ADDRESS=$EAS_ADDRESS
DEPLOYER_PRIVATE_KEY=$DEPLOYER_PRIVATE_KEY
EOF

echo ""
echo "=== Deployment Complete ==="
echo "Contract addresses written to $ENV_FILE"
